### ISSUE TITLE
800x600 canvas only?

### ISSUE THREAD

**Issue by evilC** [agrippa1994/DX9-Overlay-API#14]
Would it be possible to enable us to set the canvas size? I could do with a 1:1 ratio to game resolution.

**Comment by Nithanim** [comment]
I find that a big limitation too, so I forked it and removed the scaling. f6ef7d3c2807c1cf399135e3efc925efb710b1a1

**Comment by agrippa1994** [comment]
The canvas can be set manually with SetCalculationRatio now. https://github.com/agrippa1994/DX9-Overlay-API/commit/0b03d9c5b0517fab121556ef328689407ed2438f
