### ISSUE TITLE
Cant hook DirectX

### ISSUE THREAD

**Issue by theobeaudenon** [agrippa1994/DX9-Overlay-API#18]
Hi the api doesnt work.
I try .Init() and i get 0  

Here is files : 
![ghtyyea 1](https://cloud.githubusercontent.com/assets/3408633/6442672/cbb93598-c0f1-11e4-82ce-8e9b8ba1b5d5.png)

Here is the code:
![ziqdkxc 1](https://cloud.githubusercontent.com/assets/3408633/6442689/df662678-c0f1-11e4-94c6-a316e6ccb5b4.png)

Here is the output:
![ynjcpym 1](https://cloud.githubusercontent.com/assets/3408633/6442696/ec8b36ae-c0f1-11e4-882d-8425a8dc1774.png)

**Comment by boufle** [comment]
Same problème here :(

**Comment by JohnnyCrazy** [comment]
Hey,

The LolClient is not using DirectX in the first place (I think it's using OpenGL or sth similar).
Only the actual LeagueOfLegends.exe process is using DirectX.

Also, you should use the Wrapper this way:
```csharp
TextLabel label = new TextLabel("arial", 12, TypeFace.NONE, new Point(200, 200), Color.Red, "Hello world", true, true);
Console.WriteLine(label.Id);
```

**Comment by theobeaudenon** [comment]
Nothing in game 

![ywysk9q 1](https://cloud.githubusercontent.com/assets/3408633/6443246/efba31be-c0f5-11e4-94ca-16a991ea09cc.png)

![v1zmu4w 1](https://cloud.githubusercontent.com/assets/3408633/6443255/00948d0e-c0f6-11e4-992a-266ab0476192.png)

Maybe put space in process name ? 
![kvtj4wf 1](https://cloud.githubusercontent.com/assets/3408633/6443267/11511414-c0f6-11e4-855c-978dabcbdf64.png)

**Comment by JohnnyCrazy** [comment]
Yea, I missed the spaces.

And also, you could try to call `DX9Overlay.Init()` after SetParam

**Comment by theobeaudenon** [comment]
We must start the game first ? or launch after ?

my script must run in administrator mode ? 

nothing written in game.
![eqoc9bq 1](https://cloud.githubusercontent.com/assets/3408633/6443486/76c5d14e-c0f7-11e4-84bb-432b6ba9eb57.png)

**Comment by theobeaudenon** [comment]
i change the code : 

![48kl6mz 1](https://cloud.githubusercontent.com/assets/3408633/6443658/7f36cfd0-c0f8-11e4-84ad-34863140c4b7.png)

**Comment by agrippa1994** [comment]
What's the return value of DX9Overlay.init() ?

**Comment by theobeaudenon** [comment]
Its return 1 when the game is on

**Comment by theobeaudenon** [comment]
I try to call GetFrameRate () in the while but return always 0

**Comment by agrippa1994** [comment]
Okay, this is strange. GetFrameRate() returns -1 if an error occurs but in this case it seems to work. Do you have any other DirectX 9 based game? Maybe you can give it a try in another game.

**Comment by theobeaudenon** [comment]
I tryed on CSSGO & Binding Of Isaac.
Do you have a sample code working w/ league of legends ?

**Comment by theobeaudenon** [comment]
Its work ! Got no idea what I have done :( 
Got a question, is it possible to get a color of one pixel on the opengl screen ?

**Comment by agrippa1994** [comment]
No this is not possible because this API is only supposed to be an interface between your program and the game
