### ISSUE TITLE
BoxCreate funktioniert nicht?

### ISSUE THREAD

**Issue by readObjects** [agrippa1994/DX9-Overlay-API#20]
Hallo, alle Funktionen die ich getestet habe funktionieren einwandfrei (TextCreate, ImageCreate), nur BoxCreate möchte nicht funktionieren.

`DX9Overlay.BoxCreate(200, 100, 400, 400, &HFF000000UI, True)`
Spiel: GTA:SA

**Comment by readObjects** [comment]
Ok, lag an SA:MP... Funktioniert jetzt.

**Comment by agrippa1994** [comment]
Sry, dass ich das nochmals öffne, aber dürfte ich wissen, was der Fehler war? Ich empfehle dir für GTA diese API zu verwenden (alle Overlay-Methoden sind includiert): https://github.com/SAMPProjects/Open-SAMP-API

**Comment by readObjects** [comment]
Ich habe die SA:MP Version 0.3z installiert, aber hatte einen 0.3.7 Server in der Liste.
Also bin ich einfach auf diesen Server connected, aber die Box wurde nicht angezeigt (Ist ja klar, kein Connect zum Server möglich).
Dann bin ich auf einen 0.3z Server connected, die Verbindung wurde hergestellt, und ein Login-Dialog kam, und somit dann auch die Box.

**Comment by agrippa1994** [comment]
Okay, danke für die Bemerkung :)
