### ISSUE TITLE
Can't compile with latest Detours

### ISSUE THREAD

**Issue by GooRoo** [agrippa1994/DX9-Overlay-API#22]
Microsoft Detours 3.0 (which was released in 2012) has DetourAttach/DetourDetach instead of DetourFunction/DetourRemove which are used in DX9-Overlay-API code in Hook.

**Comment by agrippa1994** [comment]
Yes, we used Detours 1.5 and not 3.0. Maybe I provide a fix for this, but I don't know when I've got enough time for that

**Comment by GooRoo** [comment]
It's OK, I've already fixed it in my code for Detours 3.0. Thank you.

Пн, 8 черв. 2015 07:59 Manuel S. <notifications@github.com> пише:
