### ISSUE TITLE
Website is down..

### ISSUE THREAD

**Issue by AfaaGames** [agrippa1994/DX9-Overlay-API#26]
I desperately need a program that does this:
I use AMD and amd has a service called Plays.tv to record only certain games that're popular.

I really need a non-outdated software which allows me to overlay google chrome inside one of those games, so I can do a workaround and record anything without lag.

Please respond asap, there is no other alternative then using workarounds!

**Comment by JohnnyCrazy** [comment]
Website is up at http://agrippa1994.github.io/DX9-Overlay-API/
